### ISSUE TITLE
Problém s uploadem

### ISSUE THREAD

**Issue by Rinter-7** [GreysonDevel/cofit-minesweeper#1]
Nefunguje mi vaše stránka https://devel.greyson.eu/cofit/run, která slouží k vyhodnocování hry, píše mi to, že je  "Forbidden" a že nemám přístup na tuto
![Capture](https://user-images.githubusercontent.com/32569737/66950667-211fd280-f059-11e9-8f4c-a07f3ad0a328.PNG)

**Comment by paveldigana** [comment]
Omlouvám se, měli jsme špatný popis v readme v tomto projektu. Adresa pro odevzdání je https://devel.greyson.eu/soutez/ , kde jsou i pravidla soutěže.
